# see options at https://prettier.io/docs/en/options.html

#custom
singleQuote = true
jsxSingleQuote = true
printWidth = 100    

#defaults
brackSpacing = true        
bracketSameLine = false    
arrowParens = 'always'     
semi = true                
tabWidth = 2                              
useTabs = false            
